repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    -   id: check-yaml
        args:
          - --unsafe
    -   id: check-json
    -   id: detect-private-key
    -   id: debug-statements
    -   id: check-merge-conflict
# python formatting with black
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: [--line-length=120, --experimental-string-processing]
# Will run a bunch of standard pre-commit hook for jupyter notebook
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.7.0
  hooks:
    - id: nbqa-isort
    - id: nbqa-mypy
    - id: nbqa-flake8
# Run black on docstring
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==23.3.0]
# python linting with flake8
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        args:
          # HINT: ignore rules that conflicts with black formatting
          # E203: whitespace before colon
          # W503: line break before binary operator
          - --ignore=E203,W503,E501
# python import sorting with isort
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: [--profile=black, --line-length=120]
# Will autoformat the doc
- repo: https://github.com/myint/docformatter
  rev: v1.7.1
  hooks:
    - id: docformatter
      args:
        - --in-place
        - --wrap-summaries=120
        - --exclude=exploration
# Check if the format of the docstring is okay
-   repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    -   id: pydocstyle
        args:
          - --convention=google
          - --match='(?!test_).*\.py'
# Check if the docstring respect google format
-   repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
    - id: darglint
      # Exclude tests to be more flexible with people who write tests
      exclude: tests
# Check if code have security issue
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      exclude: "tests"